# Generated by Django 6.0.4 on 2026-04-14 09:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RailHealthSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rail_name', models.CharField(choices=[('UPI', 'Unified Payments Interface'), ('IMPS', 'Immediate Payment Service'), ('RTGS', 'Real Time Gross Settlement'), ('NEFT', 'National Electronic Funds Transfer'), ('NACH', 'National Automated Clearing House')], max_length=10)),
                ('success_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('latency_ms', models.IntegerField(default=0)),
                ('transactions_per_min', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('down', 'Down'), ('maintenance', 'Maintenance')], default='healthy', max_length=20)),
                ('error_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('snapshot_at', models.DateTimeField(auto_now_add=True)),
                ('raw_data', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-snapshot_at'],
                'indexes': [models.Index(fields=['rail_name', '-snapshot_at'], name='rails_railh_rail_na_9663a1_idx'), models.Index(fields=['status'], name='rails_railh_status_cdf5ad_idx')],
            },
        ),
    ]
