# Generated by Django 5.0.6 on 2026-05-03 14:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='railhealthsnapshot',
            name='snapshot_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
