# Generated by Django 6.0.4 on 2026-04-14 09:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiComplianceMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('api_name', models.CharField(choices=[('check_transaction_status', 'Check Transaction Status'), ('initiate_payment', 'Initiate Payment'), ('balance_enquiry', 'Balance Enquiry'), ('validate_vpa', 'Validate VPA')], max_length=50)),
                ('tps_current', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('tps_limit', models.DecimalField(decimal_places=2, default=3.0, max_digits=8)),
                ('calls_last_minute', models.IntegerField(default=0)),
                ('calls_last_hour', models.IntegerField(default=0)),
                ('violation_count', models.IntegerField(default=0)),
                ('is_compliant', models.BooleanField(default=True)),
                ('measured_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-measured_at'],
                'indexes': [models.Index(fields=['api_name', '-measured_at'], name='compliance__api_nam_316153_idx'), models.Index(fields=['is_compliant'], name='compliance__is_comp_800083_idx')],
            },
        ),
        migrations.CreateModel(
            name='ComplianceViolation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('api_name', models.CharField(max_length=50)),
                ('tps_observed', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tps_limit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('violation', 'Violation'), ('critical', 'Critical')], max_length=10)),
                ('description', models.TextField()),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='compliance.apicompliancemetric')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
    ]
