# Generated by Django 6.0.4 on 2026-04-14 09:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rail_name', models.CharField(default='UPI', max_length=10)),
                ('classification', models.CharField(choices=[('NPCI_SIDE', 'NPCI Infrastructure Issue'), ('BANK_SIDE', 'Bank-side Failure'), ('FALSE_POSITIVE', 'False Positive'), ('UNKNOWN', 'Under Investigation')], default='UNKNOWN', max_length=20)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('false_positive', 'False Positive')], default='active', max_length=20)),
                ('title', models.CharField(default='Payment rail degradation detected', max_length=200)),
                ('classifier_reasoning', models.TextField(blank=True)),
                ('historical_match', models.CharField(blank=True, max_length=200)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('rail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='rails.railhealthsnapshot')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_type', models.CharField(choices=[('rail_monitor', 'Rail Monitor'), ('incident_classifier', 'Incident Classifier'), ('rerouting_advisor', 'Rerouting Advisor'), ('compliance_watchdog', 'Compliance Watchdog'), ('comms_generator', 'Communication Generator')], max_length=30)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('input_data', models.JSONField(default=dict)),
                ('output_data', models.JSONField(default=dict)),
                ('duration_ms', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='incidents.incident')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ReroutingRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_rail', models.CharField(max_length=10)),
                ('to_rail', models.CharField(max_length=10)),
                ('confidence', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('rationale', models.TextField()),
                ('estimated_success_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rerouting', to='incidents.incident')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status'], name='incidents_i_status_9a4f12_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['rail_name', '-detected_at'], name='incidents_i_rail_na_c4ff17_idx'),
        ),
    ]
