[phases.install]
cmds = [
  "python -m ensurepip --upgrade",
  "python -m pip install --break-system-packages -r requirements.txt"
]

[start]
cmd = "python manage.py migrate && python manage.py seed_demo && daphne config.asgi:application --port $PORT --bind 0.0.0.0"